version: '3.5'
services:
    mysql_db:
        image: mysql:5.7
        container_name: ai_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ai_db
            MYSQL_USER: research
            MYSQL_PASSWORD: research
        volumes:
            - ./data/common_db/conf.d:/etc/mysql/conf.d
        ports:
            - "33060:33060"
    jupyter:
        build:
            context: .
            dockerfile: ./Dockerfile
        user: root
        volumes:
            - ./home:/home
        ports:
            - "8888:8888"
        command: jupyter lab --allow-root --ip=0.0.0.0 --no-browser
volumes:
    mysql-storage:
        driver: local
