FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

MAINTAINER music-brain88 <music.brain88@gmail.com>

# setting cuda path
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib:/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
ENV CUDA_HOME="/usr/local/cuda"

ENV VIRTUAL_ENV=/home/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN perl -p -i.bak -e 's%https?://(?!security)[^ \t]+%http://ftp.jaist.ac.jp/pub/Linux/ubuntu/%g' /etc/apt/sources.list``
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y \
    locales \
    unzip \
    python3-all-dev \
    python3-pip \
    python3-venv \
    mecab \
    libmecab-dev \
    mecab-ipadic-utf8 \
    git \
    curl \
    make \
    sudo \
    pkg-config \
    libcairo2-dev \
    gobject-introspection \
    libgirepository1.0-dev \
    apt-utils \
    npm \
    neovim \
    nginx \
    gosu

RUN python3 -m venv  $VIRTUAL_ENV

RUN rm -rf /root/.cache
RUN pip3 install --upgrade pip

RUN locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

# for jupyter extension
RUN npm install -g n

RUN n 12.13.1

RUN pip3 install --upgrade pip
RUN pip3 install poetry==0.12.17


WORKDIR /home

COPY env/poetry.lock ./poetry.lock
COPY env/pyproject.toml ./pyproject.toml

RUN poetry install
RUN poetry add trains

RUN node -v
RUN echo "build jupyter extension"
RUN poetry run jupyter labextension install @jupyterlab/toc
#RUN poetry run jupyter labextension install @jupyterlab/plotly-extension
RUN poetry run jupyter labextension install @krassowski/jupyterlab-lsp

RUN mkdir workspace
