FROM ubuntu:16.04

MAINTAINER music-brain88 <music.brain88@gmail.com>

RUN apt-get -y update && apt-get install -y \
         wget \
         curl \
         python3.5-dev \
         nginx \
         ca-certificates \
         mecab \
         libmecab-dev \
         mecab-ipadic \
         mecab-ipadic-utf8 \
         git \
         make \
         xz-utils \
         file \
         sudo \
         swig \
         nano \
         vim \
         emacs \
         locales \
         patch \
         build-essential \
         ssh \
         npm \
         zip \
         unzip \
&& rm -rf /var/lib/apt/lists/*

RUN locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8


RUN wget https://bootstrap.pypa.io/3.3/get-pip.py && python3.5 get-pip.py && \
rm -rf /root/.cache

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

RUN pip3 install --upgrade pip

COPY requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app
RUN pip3 install -r requirements.txt

RUN npm install -g n

RUN n list

RUN n latest
RUN echo node version:
RUN node -v
RUN echo "build jupyter extension"
RUN jupyter labextension install @jupyterlab/toc
WORKDIR /home
