name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Install Docker
        run: brew cask install docker
      - name: install docker-compose
        run: brew install docker-compose
      - name: Docker daemon start
        run: open /Applications/Docker.app
      - name: build on ${{matrix.os}}
        run: docker-compose -f docker-compose-darwin.yml build
